[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sshine/mxroute-rs"
homepage = "https://github.com/sshine/mxroute-rs"

[workspace.lints.rust]
unused_must_use = "deny"

[workspace.lints.clippy]
expect_used = "deny"
unwrap_used = "deny"
